Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -49,8 +49,24 @@ jobs:
               container_id=$(docker ps --format "{{.ID}} {{.Names}}" | grep gitflask$ | awk '{print $1}')
               container_name=$(docker ps --format "{{.ID}} {{.Names}}" | grep gitflask$ | awk '{print $2}')
               echo "Container ID : ${container_id} to be deleted"
+              docker container kill ${container_id}
+              docker container rm -f ${container_name}
+              if [[ $? -eq 0 ]]
+              then
+                echo "Container Deleted Successfully !!!!!"
+                docker pull dhananjaypuri/gitpython:latest
+                docker container run -d --name gitflask -p 5000:5000 dhananjaypuri/gitpython
+                if [[ $? -eq 0 ]]
+                then
+                  echo "Container Started Successfully !!!!!"
+                else
+                  echo "Container cannot be started"
+                fi
+              else
+                echo "Container cannot be deleted"
+              fi 
             else
-              echo "Container already running"
+              echo "Starting container as it was not running !!!!!!!!"
               docker pull dhananjaypuri/gitpython:latest
               docker container run -d --name gitflask -p 5000:5000 dhananjaypuri/gitpython
               if [[ $? -eq 0 ]]
